package collections;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class test {

	public static void main(String[] args) {
		// TODO Autogenerated method stub
		List<Integer> list =  new ArrayList<>(Arrays.asList(1,4,3,6,4,2));

//		System.out.println(list.size());
		Integer min = 0;
//		for(int i = 0; i < list.size(); i++) {
//			if(list.get(i) < min) {
//				min = list.get(i);
//			}
//		}
//		System.out.println(min);
		for(int j = 0; j < list.size(); j++) {
			for(int n : list) {
				if(list.get(j) < n) {
					min = list.get(j);
				}
			}
		}
		System.out.println(min);

		
	}

}
